name: Python Application Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 8000:8000

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-fastapi-app

    - name: Run the Docker container
      run: docker run -d -p 8000:8000 my-fastapi-app

    - name: Install dependencies for the test
      run: sudo apt-get install -y curl

    - name: Wait for application to start
      run: sleep 10  # Adjust this based on how long your app takes to start

    - name: Check if the API is up and running
      run: curl --fail http://localhost:8000/ || exit 1

    # Insert additional test steps here if necessary

    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Run flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
